### ISSUE TITLE
Please publish 5.11.9

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/bower-dist#16]
@feryardiant I'd be happy to do this too, but I'm not quite sure how. Also, if this could be automagically published, via say travis-ci, that would be even better #10. 

Here's the release notes for 5.11.9, if you are interested: https://github.com/FineUploader/fine-uploader/releases/tag/5.11.9

**Comment by rnicholus** [comment]
🙇

**Comment by feryardiant** [comment]
@rnicholus pardon me for being super late..
I had bunch of jobs in my office lately..

**Comment by rnicholus** [comment]
No need to apologize. Thanks for your work on this.
